//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Order_Detail = new HashSet<Order_Detail>();
        }
    
        /// <summary>
    	/// 
    	/// </summary>
    	public long Id { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public long MemberId { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public long ReceiverId { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public int Quantity { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public decimal TotalPrice { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public int Status { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public System.DateTime CreateTime { get; set; }
    
        public virtual Member Member { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Detail> Order_Detail { get; set; }
        public virtual Receiver Receiver { get; set; }
    }
}
