//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Store()
        {
            this.Classes = new HashSet<Class>();
        }
    
        /// <summary>
    	/// 
    	/// </summary>
    	public long Id { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public long MemberId { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string Name { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public string HostUrl { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public System.DateTime ExpireTime { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public int Status { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public long CreateBy { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public System.DateTime CreateTime { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public long UpdateBy { get; set; }
        /// <summary>
    	/// 
    	/// </summary>
    	public System.DateTime UpdateTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Class> Classes { get; set; }
        public virtual Member Member { get; set; }
    }
}
